services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ajserp
      MYSQL_USER: gayu
      MYSQL_PASSWORD: gayu123
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # <-- this line ensures persistence

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    restart: always
    ports:
      - "5000:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql_data:  # <-- declare the named volume here