# Generated by Django 5.2.5 on 2025-10-28 07:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('hsn_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='HSN Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'HSN Code',
                'verbose_name_plural': 'HSN Codes',
                'ordering': ['hsn_code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialBrand',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('alt_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_number', models.CharField(max_length=15)),
                ('pan_no', models.CharField(max_length=10)),
                ('credit_period', models.IntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('state_of_supply', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='suppliers/')),
                ('billing_address1', models.TextField()),
                ('billing_address2', models.TextField(blank=True, null=True)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(max_length=100)),
                ('billing_country', models.CharField(default='India', max_length=100)),
                ('billing_postal_code', models.CharField(max_length=10)),
                ('shipping_address1', models.TextField()),
                ('shipping_address2', models.TextField(blank=True, null=True)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=100)),
                ('shipping_country', models.CharField(default='India', max_length=100)),
                ('shipping_postal_code', models.CharField(max_length=10)),
                ('same_as_billing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierGroup',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=70)),
                ('contact_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('state_of_supply', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=15)),
                ('address1', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('alt_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_number', models.CharField(max_length=15)),
                ('pan_no', models.CharField(max_length=10)),
                ('credit_period', models.IntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('state_of_supply', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='customers/')),
                ('billing_address1', models.TextField()),
                ('billing_address2', models.TextField(blank=True, null=True)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(max_length=100)),
                ('billing_country', models.CharField(default='India', max_length=100)),
                ('billing_postal_code', models.CharField(max_length=10)),
                ('shipping_address1', models.TextField()),
                ('shipping_address2', models.TextField(blank=True, null=True)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=100)),
                ('shipping_country', models.CharField(default='India', max_length=100)),
                ('shipping_postal_code', models.CharField(max_length=10)),
                ('same_as_billing', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, db_column='customer_category_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajserp.customercategory')),
                ('customer_group', models.ForeignKey(blank=True, db_column='customer_group_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajserp.customergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('category', models.CharField(choices=[('Service', 'Service'), ('Spare', 'Spare'), ('Material', 'Material')], max_length=20, primary_key=True, serialize=False)),
                ('material_code', models.CharField(editable=False, max_length=50)),
                ('material_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50)),
                ('hsn_code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/')),
                ('active_status', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, db_column='brand_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajserp.materialbrand')),
                ('model', models.ForeignKey(blank=True, db_column='model_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajserp.materialmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pricing_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(db_column='material_category', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='ajserp.material')),
            ],
            options={
                'ordering': ['-from_date'],
                'unique_together': {('material', 'from_date')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='current_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_material', to='ajserp.pricelist', verbose_name='Current Price'),
        ),
        migrations.CreateModel(
            name='MaterialInward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grn_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('batch', models.CharField(editable=False, max_length=100, unique=True)),
                ('grn_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(blank=True, choices=[('Service', 'Service'), ('Spare', 'Spare'), ('Material', 'Material')], max_length=20, null=True)),
                ('material_code', models.CharField(editable=False, max_length=50)),
                ('material_name', models.CharField(editable=False, max_length=255)),
                ('uom', models.CharField(editable=False, max_length=50)),
                ('vendor_name', models.CharField(editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, db_column='brand_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajserp.materialbrand')),
                ('hsn_code', models.ForeignKey(db_column='hsn_code', on_delete=django.db.models.deletion.CASCADE, to='ajserp.hsncode', verbose_name='HSN Code')),
                ('model', models.ForeignKey(blank=True, db_column='model_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajserp.materialmodel')),
                ('vendor', models.ForeignKey(db_column='vendor_code', on_delete=django.db.models.deletion.CASCADE, to='ajserp.supplier', to_field='vendor_code', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Material Inward',
                'verbose_name_plural': 'Material Inwards',
                'ordering': ['-grn_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.ForeignKey(blank=True, db_column='supplier_category_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajserp.suppliercategory'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_group',
            field=models.ForeignKey(blank=True, db_column='supplier_group_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajserp.suppliergroup'),
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hsn_code', models.ForeignKey(db_column='hsn_code', on_delete=django.db.models.deletion.CASCADE, to='ajserp.hsncode', verbose_name='HSN Code')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
            },
        ),
    ]
