# Generated by Django 5.2.5 on 2025-10-13 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('alt_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_group', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(max_length=15)),
                ('pan_no', models.CharField(max_length=10)),
                ('credit_period', models.IntegerField(default=0)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('state_of_supply', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='customers/')),
                ('billing_address1', models.TextField()),
                ('billing_address2', models.TextField(blank=True, null=True)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(max_length=100)),
                ('billing_country', models.CharField(default='India', max_length=100)),
                ('billing_postal_code', models.CharField(max_length=10)),
                ('shipping_address1', models.TextField()),
                ('shipping_address2', models.TextField(blank=True, null=True)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=100)),
                ('shipping_country', models.CharField(default='India', max_length=100)),
                ('shipping_postal_code', models.CharField(max_length=10)),
                ('same_as_billing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('hsn_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cess', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=70)),
                ('contact_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('state_of_supply', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=15)),
                ('address1', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_code', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/')),
                ('active_status', models.BooleanField(default=True)),
                ('taxes', models.ForeignKey(db_column='hsn_code', on_delete=django.db.models.deletion.CASCADE, to='ajserp.taxes')),
            ],
        ),
    ]
