# Generated by Django 5.2.5 on 2025-12-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajserp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Terms & Conditions',
                'verbose_name_plural': 'Terms & Conditions',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='pagepermission',
            name='key',
            field=models.CharField(db_column='key', max_length=255),
        ),
        migrations.RenameField(
            model_name='pagepermission',
            old_name='key',
            new_name='page_name',
        ),
        migrations.AlterUniqueTogether(
            name='pagepermission',
            unique_together={('user', 'page_name')},
        ),
    ]
